# Bem-vindo {.unnumbered}

**Análise de Dados para Biocientistas** é um livro interativo concebido para transformar a forma como os dados são analisados nas ciências da vida. 

> *Na ciência, muitos caminham sobre a frágil vidraça da intuição. Mas quando a complexidade biológica do mundo real estilhaça essa superfície, o pesquisador é lançado em queda livre num oceano de incertezas, cercado por ruídos e variáveis. Nesse momento, a estatística deixa de ser apenas matemática e torna-se a sua rede de segurança. Ela é a linguagem que transforma o caos das distribuições e dos p-valores em terra firme, provando que, para compreender a vida, é preciso primeiro ter coragem para quebrar a superfície.*

### Ficha Técnica
* **Autor:** Márcio Luís Moreira de Souza
* **ISBN:** 978-X-XXXX-XXXX-X
* **DOI:** [10.XXXX/zenodo.XXXXX](https://doi.org/10.XXXX/zenodo.XXXXX)
* **Licença:** Este material é disponibilizado sob a licença Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0).

---

Para iniciar a leitura e interagir com os códigos em tempo real, utilize a barra de navegação lateral e avance para o **Capítulo 1: Introdução ao método estatístico**.